### ISSUE TITLE
Memory issues even on some Express boards

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_HT16K33#103]
Re this thread:
https://forums.adafruit.com/viewtopic.php?p=938210

Can recreate via simple REPL import:
```python
Adafruit CircuitPython 7.3.2 on 2022-07-20; Adafruit Feather M0 Express with samd21g18
>>> import adafruit_ht16k33.segments
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ht16k33/segments.py", line 484, in <module>
MemoryError: memory allocation failed, allocating 96 bytes
>>> 
```

**Comment by makermelissa** [comment]
It was recently updated to support multiple displays. Perhaps it could be optimized a little by splitting it up some more and then just loading the necessary stuff. As a quick fix, the user could use an older version for now.
